version: '3'
services:
  
  cassandra:
    image: bitnami/cassandra
    restart: on-failure
    ports:
      - 7000:7000
      - 9042:9042
    expose:
      - 7000
      - 7001
      - 7199
      - 9042 
      - 9142
    volumes:
      - ./cassandra:/bitnami
    environment:
      - CASSANDRA_SEEDS=cassandra,cassandra2,cassandra3
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M

  cassandra2:
    image: bitnami/cassandra
    restart: on-failure
    ports:
      - 7001:7000
      - 9043:9042
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9142
    volumes:
      - ./cassandra2:/bitnami
    environment:
      - CASSANDRA_SEEDS=cassandra,cassandra2,cassandra3
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
  
  cassandra3:
    image: bitnami/cassandra
    restart: on-failure
    ports:
      - 7002:7000
      - 9044:9042
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9142
    volumes:
      - ./cassandra3:/bitnami
    environment:
      - CASSANDRA_SEEDS=cassandra,cassandra2,cassandra3
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M



